language: python
python:
 - "2.7"
virtualenv:
  system_site_packages: true
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - "sudo apt-get update"
 - "sudo apt-get --no-install-recommends install python-numpy python-scipy python-matplotlib libhdf5-serial-dev gfortran"
 - "mkdir -p ~/.matplotlib/; echo 'backend : Agg' > ~/.matplotlib/matplotlibrc"
 - "pip install h5py cython --use-mirrors"
 - "git clone https://github.com/molmod/molmod.git; cd molmod; python setup.py install; cd .."
 - "python setup.py install"
script:
 - "cd; nosetests -v yaff"
