sudo: false
language: python
python:
 - "2.7"
addons:
  apt:
    packages:
    - libhdf5-serial-dev
branches:
  except:
    # skip version tags
    /^\d+\.\d+(\.\d+)$/
install:
 - pip install --upgrade pip
 - pip install subprocess32 functools32
 - "pip install --only-binary :all: scipy matplotlib h5py cython"
 - pip install molmod
 - mkdir -p ~/.config/matplotlib/
 - echo backend:agg > ~/.config/matplotlib/matplotlibrc
 - python setup.py install --single-version-externally-managed --record=record.txt
script:
 - "cd; nosetests -v yaff --processes=2 --process-timeout=100"
