package:
  version: "{{ load_setup_py_data().version }}"
  name: 'yaff'

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_1
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - numpy >=1.5
    - cython >=0.26
    - setuptools
  run:
    - python
    - numpy >=1.5
    - molmod >=1.4.1
    - h5py
    - scipy
    - matplotlib

test:
  imports:
    - yaff

about:
  dev_url: https://github.com/molmod/yaff
  description: YAFF is yet another force-field code
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: YAFF is yet another force-field code
  home: http://molmod.github.io/yaff
  license_file: COPYING
  doc_url: http://molmod.github.io/yaff

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
