package:
  version: "{{ load_setup_py_data().version }}"
  name: 'yaff'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numpy >=1.5
    - nose
    - molmod >=1.4.1
    - h5py
    - scipy
    - matplotlib
  build:
    - python
    - numpy >=1.5
    - nose
    - molmod >=1.4.1
    - h5py
    - scipy
    - matplotlib
    - cython >=0.26
    - setuptools

about:
  dev_url: https://github.com/molmod/yaff
  description: YAFF is yet another force-field code
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: YAFF is yet another force-field code
  home: http://molmod.github.io/yaff
  license_file: LICENSE.txt
  doc_url: http://molmod.github.io/yaff

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
